### ISSUE TITLE
v0.4.0: 'ModelObstype' object has no attribute 'is_compatible_with'

### ISSUE THREAD

**Issue by NoahVerhoeven** [vergauwenthomas/MetObs_toolkit#490]
![Image](https://github.com/user-attachments/assets/0f01ab8e-4e77-4c94-a2b2-dbb73f91b199)

While trying to get the `fill_gaps_with_debiased_modeldata` method to work in v0.4.0 I encountered the error show above. Without this check the method works fine. For reference, in my script ERA5-modeldata is obtained through a function `get_era5`, the functionality of which can be seen in the screenshot below.

![Image](https://github.com/user-attachments/assets/0a0e558f-c895-4415-b51d-43def45afbc8)

**Comment by vergauwenthomas** [comment]
@NoahVerhoeven  On it! These bugs are normally captured by the test, but i saw that there are no test at the moment on gapfilling in v0.4.0, so i will put that on my agenda for today.

**Comment by vergauwenthomas** [comment]
solved in #489
